/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.aagenda.braille;

import java.util.LinkedList;
import java.util.List;
import javax.swing.JPanel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import pl.aagenda.braille.character.CharacterBuilder;
import pl.aagenda.braille.character.Dots;
import pl.aagenda.braille.gui.CharacterDisplayJPanel;
import pl.aagenda.braille.gui.RowJPanel;

/**
 *
 * @author mryohan
 */
public class MainJFrame extends javax.swing.JFrame {
    private static final Logger logger = LogManager.getLogger(MainJFrame.class);
    
    private Configuration configuration = ConfigurationManager.getDefaultConfiguration();
    
    private List<Integer> keysPressed = new LinkedList();
    
    private CharacterBuilder cb = new CharacterBuilder();
    
    private int row = 0;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
//        StringBuilder sb = new StringBuilder();
//        for (char i = 'a'; i <= 'z'; i++) {
//            sb.append(i);
//        }
//        jLabel1.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Braille Simulator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        logger.debug("Pressed " + evt.getKeyChar() + "(" + evt.getKeyCode() + ")");
        char ch = evt.getKeyChar();
        ch = Character.toLowerCase(ch);
        
        if (ch == 10) {
            row++;
        }
        
        if (ch == configuration.getKeyLB() ||
                ch == configuration.getKeyLM() ||
                ch == configuration.getKeyLT() ||
                ch == configuration.getKeyRB() ||
                ch == configuration.getKeyRM() ||
                ch == configuration.getKeyRT()) {
        
            keysPressed.add(Integer.valueOf(ch));

            if (configuration.getKeyLT() == ch) {
                cb.addDot(Dots.LT);
            }
            if (configuration.getKeyLM() == ch) {
                cb.addDot(Dots.LM);
            }
            if (configuration.getKeyLB() == ch) {
                cb.addDot(Dots.LB);
            }
            if (configuration.getKeyRT() == ch) {
                cb.addDot(Dots.RT);
            }
            if (configuration.getKeyRM() == ch) {
                cb.addDot(Dots.RM);
            }
            if (configuration.getKeyRB() == ch) {
                cb.addDot(Dots.RB);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        logger.debug("Released " + evt.getKeyChar() + "(" + evt.getKeyCode() + ")");
        char ch = evt.getKeyChar();
        ch = Character.toLowerCase(ch);
        
        if (ch == configuration.getKeyLB() ||
                ch == configuration.getKeyLM() ||
                ch == configuration.getKeyLT() ||
                ch == configuration.getKeyRB() ||
                ch == configuration.getKeyRM() ||
                ch == configuration.getKeyRT()) {
            keysPressed.remove(Integer.valueOf(ch));
            if (keysPressed.isEmpty()) {
                logger.debug("Setting new JPanel");
                JPanel child = new CharacterDisplayJPanel(cb.build());
                logger.debug("JPanel got " + jPanel1.getComponentCount() + " components");
                while (jPanel1.getComponentCount() <= row) {
                    jPanel1.add(new RowJPanel());
                }
                JPanel panel = (JPanel) jPanel1.getComponent(row);
                panel.add(child);
                panel.revalidate();
                panel.repaint();
                logger.debug(child);
                cb.clear();
            }
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.error(ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
