package pl.aagenda.braille.gui;

import java.awt.Color;
import java.awt.Graphics2D;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import pl.aagenda.braille.model.character.Dots;

/**
 *
 * @author mryohan
 */
public class CharacterDisplayJPanel extends javax.swing.JPanel {
    private static final Logger logger = LogManager.getLogger(CharacterDisplayJPanel.class);
    public final static int s = 16;
    public final static int d = 8;
    private final pl.aagenda.braille.model.character.Character c;

    /**
     * Creates new form CharacterDisplayJPanel
     * @param c
     */
    public CharacterDisplayJPanel(pl.aagenda.braille.model.character.Character c) {
        initComponents();
        this.c = c;
    }
    
    @Override
    public void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (c != null) {
            Graphics2D graphics = (Graphics2D) g;
            graphics.setColor(Color.BLACK);
            for (Dots d : c.getDots()) {
                switch (d) {
                    case LT:
                        graphics.fillOval(0, 0, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case LM:
                        graphics.fillOval(0, s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case LB:
                        graphics.fillOval(0, 2 * s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RT:
                        graphics.fillOval(s, 0, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RM:
                        graphics.fillOval(s, s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RB:
                        graphics.fillOval(s, 2 * s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(24, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        logger.debug("Clicked in " + toString());
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public String toString() {
        return super.toString() + ", CharacterDisplayJPanel{" + "c=" + c + '}';
    }
}
