package pl.aagenda.braille.gui;

import java.awt.Color;
import java.awt.Graphics2D;
import pl.aagenda.braille.character.Dots;

/**
 *
 * @author mryohan
 */
public class CharacterDisplayJPanel extends javax.swing.JPanel {
    public final static int s = 32;
    public final static int d = 8;
    private final pl.aagenda.braille.character.Character c;

    /**
     * Creates new form CharacterDisplayJPanel
     * @param c
     */
    public CharacterDisplayJPanel(pl.aagenda.braille.character.Character c) {
        initComponents();
        this.c = c;
    }
    
    @Override
    public void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (c != null) {
            Graphics2D graphics = (Graphics2D) g;
            graphics.setColor(Color.BLACK);
            for (Dots d : c.getDots()) {
                switch (d) {
                    case LT:
                        graphics.fillOval(0, 0, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case LM:
                        graphics.fillOval(0, s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case LB:
                        graphics.fillOval(0, 2 * s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RT:
                        graphics.fillOval(s, 0, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RM:
                        graphics.fillOval(s, s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                    case RB:
                        graphics.fillOval(s, 2 * s, CharacterDisplayJPanel.d, CharacterDisplayJPanel.d);
                        break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public String toString() {
        return super.toString() + ", CharacterDisplayJPanel{" + "c=" + c + '}';
    }
}
